### ISSUE TITLE
Adding and Deleting Components in a Single Deployment

### ISSUE THREAD

**Issue by MaciekLeks** [scolladon/sfdx-git-delta#103]
I'm wondering if you try to use Single Deployment for add/mod/del? If yes, please let us know how to do this with the plugin. To use single deployment according to [SF](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_deploy_deleting_files.htm) we need to add metadata to be deleted.

**Comment by scolladon** [comment]
Hi @MaciekLeks !

Thanks for your interest in the plugin !

In fact it is not possible yet using the force:source:deploy command because it just don't accept destructiveChanges.xml
This is the reason why we propose to do it in two times

1. Deploy using force:source:deploy the added/modified elements using the package.xml in the package folder of the output or the delta metadata file generated.
2. Delete using force:mdapi:deploy the deleted element using the other using the destructiveChanges.xml in the destructiveChanges folder

As soon as it will be possible to delete and deploy at the same time using force:source command we will update the readme !
Stay tuned

**Comment by MaciekLeks** [comment]
Yes, we are waiting [(188)](https://github.com/forcedotcom/cli/issues/188) but no matter if we use mdapi or sfdx api we need deleted parts to be get rid of them. You use mdapi anyway, so maybe this feature do not have to wait :) It's really hard to manage consistency of the org when deployment of add/mod changes succeded but the destructive changes not.
