### ISSUE TITLE
Moving a metadata file ends with destructing the metadata

### ISSUE THREAD

**Issue by MaciekLeks** [scolladon/sfdx-git-delta#107]
## What is the problem

Moving file from one place to another treats it as: modification and removing.

We have a change `git diff --name-status HASH1 HASH2`:
```
R093	force-app/common/permissionsetgroups/DealerSupport.permissionsetgroup-meta.xml	force-app/sales/permissionsetgroups/DealerSupport.permissionsetgroup-meta.xml
```
Then after running the code:
`sfdx sgd:source:delta --to HASH2 --from HASH1 --output sgd  --generate-delta`
This metadata sits in:
- destructiveChanges.xml
- package.xml

Due to the fact we cannot control pre and post deletion we use post deletion always. 

So once the metadata is deployed it's deleted in detructiveChanges deploy step.

In your code you use `--no-renames` so the result is always: D and A for `git diff` :)

### What is parameter and their value you used

``sfdx sgd:source:delta --to HASH2 --from HASH1 --output sgd  --generate-delta``

### What is the expected result

Moved files should not be part of desctructiveChanges.xml

### What is the actual result

Deploying a moved metdadat  and then it's being deleted.

## Steps to reproduce

1. Create a metadata
2. Deploy it using sgd artifacts (deploy changes and destructive changes)
3. Move the medatada to other directory and commit the changes
4. Deploy it using sgd artifacts (deply chanes and destructive changes)

## Execution context
Version: The latest one installed in gitlab runner everytime the job starts

**Comment by scolladon** [comment]
Hi @MaciekLeks !

Thanks for your interest on the plugin.
You are totally right, the code uses the `--no-renames` git diff parameter in order to deal with the file renaming the way the metadata does.

So I think the issue here is when the path is changed (not the filename) it is treated has a renaming by git and then the algorithm treat them independently (destructiveChanges.xml and package.xml) which is not what we want in this situation.

I will design a fix for this behaviour in the next days and we will ship this as patch
