### ISSUE TITLE
sgd:source:delta produces error: Value is not defined

### ISSUE THREAD

**Issue by Thieveryshoe** [scolladon/sfdx-git-delta#125]
Issue verification check :

- [X] does the current repository is fully deployable at the commit sha given to the from parameter of the command ?

## What is the problem

---

When I run sfdx sgd:source:delta --to HEAD --from HEAD^ --output . a package.xml file is not created.

### What is parameter and their value you used

na

### What is the expected result

Expecting a ./package/package.xml file with only files that are different to be created

### What is the actual result

ERROR running sgd:source:delta:  Value is not defined

## Steps to reproduce

---

## Execution context

---

v14.16.0
git version 2.30.1.windows.1
sfdx-cli/7.93.1 win32-x64 node-v14.16.0
@salesforce/sfdx-diff 0.0.6
org 1.6.0
salesforcedx 51.5.0
├─ limits 1.0.4
├─ schema 1.0.4
├─ apex 0.1.4
├─ custom-metadata 1.0.11
├─ user 1.2.0
├─ templates 51.3.0
├─ @salesforce/sfdx-plugin-lwc-test 0.1.7
└─ salesforce-alm 51.6.3
sfdx-git-delta 4.3.1

## Optional more information

---

I am able to use the the command successfully in a different project/repo without issue.

**Comment by Thieveryshoe** [comment]
I found a difference between the two projects.

In the project where the command does not work, my sfdx-config.json file looks like:
```json
{
  "defaultusername": "UAT",
  "packageDirectories": [
    {
      "path": "force-app", "default": true
    },
    {
      "path": "package"
    }
  ]
}
```

The file looks like this in my project where the command does work:

```
{
  "defaultusername": "UAT"
}
```

When I remove the packageDirectories item out of the config file, the command does work.

**Comment by scolladon** [comment]
Hi @Thieveryshoe !

Thanks for this very well described issue !

I have looked at it and it appears to me that maybe you have mix two files

1. [.sfdx/sfdx-config.json](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_dev_cli_config_values.htm) which contains the CLI configuration for the current workspace (probably in the git ignore because it contains information from the devhub you use etc)
2. [sfdx-project.json](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file.htm) which define the project configuration

Is it possible that, int the example you show, the sfdx-project.json information are in the sfdx-config.json ? Which create an issue with the SFDX CLI itself as it cannot parse anymore the sfdx-config.json ?

**Comment by Thieveryshoe** [comment]
Ah this does appear to be the issue!  Too many similarly named items when it comes to working with SFDX stuff.

I removed the packageDirectories entry from the .sfdx/sfdx-configs.json file and the diff worked as expected.

Also,  thanks for the links, I'll have a look at them to refresh myself on which files are used for what.
