### ISSUE TITLE
EmailTemplate members with antislashes on Windows should be with slashes

### ISSUE THREAD

**Issue by nvuillam** [scolladon/sfdx-git-delta#127]
On Windows, generated EmailTemplate items in package.xml contain antislashes instead of slashes

So to be able to deploy after, I have to replace \ by /

Example :

```xml
  <types>
    <name>EmailTemplate</name>
    <members>unfiled$public</members>
    <members>unfiled$public\ChantierJ14DateDemarrage</members>
    <members>unfiled$public\ChantierReferenceMarketing</members>
    <members>unfiled$public\NotifDemandePromo</members>
  </types>
```

should be

```xml
  <types>
    <name>EmailTemplate</name>
    <members>unfiled$public</members>
    <members>unfiled$public/ChantierJ14DateDemarrage</members>
    <members>unfiled$public/ChantierReferenceMarketing</members>
    <members>unfiled$public/NotifDemandePromo</members>
  </types>
```

Would it be possible to solve this issue ? Or tell me where to do it, so I can make a PR ? Thanks :)

**Comment by scolladon** [comment]
Hi @nvuillam!

Thanks for raising this issue!

The code of the plugin is platform robust because it uses path.sep everywhere. It even normalize git path returned from git diff --name-status (which is POSIX) to be compliant with the running architecture.

The issue here is that we use this path separator everywhere and also in the metadata component.
The fix will be to generate the package.xml using POSIX file path separator then

I'll try to find some times EOW to identify where it comes from and fix it.

If you are available for the PR review that would be awesome!

**Comment by nvuillam** [comment]
@scolladon Sure I can validate your future PR by fetching the PR branch and test locally with sfdx plugins:link ;)
ps: thanks for your great tool :)

**Comment by scolladon** [comment]
@nvuillam [PR](https://github.com/scolladon/sfdx-git-delta/pull/128) ready for review :)

**Comment by nvuillam** [comment]
@scolladon I'm sorry ... but not working yet :/
![image](https://user-images.githubusercontent.com/17500430/115124117-d6ba4180-9fc0-11eb-8f29-3663dfff2321.png)

**Comment by nvuillam** [comment]
mmmm I didn't checkout the good branch, sorry, i check again ^^

**Comment by nvuillam** [comment]
Works like a charm :) :)

Thanks a lot for your reactivity, and for your great plugin that allows us to not have to update manually package.xml & destructiveChange.xml in our sfdx-projects ;)

![image](https://user-images.githubusercontent.com/17500430/115124211-665ff000-9fc1-11eb-9cee-3d580a4e27b9.png)

**Comment by nvuillam** [comment]
I'll reopen when it will be released^^

**Comment by scolladon** [comment]
Thanks for your help @nvuillam !

**Comment by nvuillam** [comment]
You're welcome, glad I could help :)

**Comment by scolladon** [comment]
New version 4.3.2 released !
