### ISSUE TITLE
Possibility of pushing all profiles/permission sets

### ISSUE THREAD

**Issue by mateuszzw** [scolladon/sfdx-git-delta#163]
### Is your proposal related to a problem?

Currently, the solution doesn't allow to push all profiles if needed - in specific situations it's causing deployment failures.

### Describe the solution you'd like

The flag that would allow all profiles or permission sets to be included in the package.xml (wildcard)

**Comment by scolladon** [comment]
Hi @mateuszzw !

Thanks for your interest in the plugin.

At first sight I would say that this is not the responsibility of the plugin, but let see.

Is it possible to detect those specific situations making deployment failure because profile and permission set are not present and how ?

Here is a workaround I can propose : 
```sh
$ sfdx sgd:source:delta [...params]
$ mv path/to/profiles/* output/path/to/profiles
$ mv path/to/permissionsets/* output/path/to/permissionsets
```

**Comment by mehdisfdc** [comment]
Hi @mateuszzw, thank you for proposing this enhancement!

Yo understand your request a bit better, I have 2 questions:

1) (a) Are you dealing in a situation where the profile has been changed in the repo, but SGD failed to pick this changed profile? (which sounds like a a bug to me). Or (b) are you willing to re-deploy profiles even when they did not change in the repo?

2) If we are in situation "b", what makes the profiles or permission sets different from the other metadata in your repo, that would justify SGD to always include them?
The reason why I'm asking this is because SGD is here to help you deploy only the metadata that changed. 
When you are not interested in identifying the files that actually changed since a reference commit, you can simply run a `sfdx force:source:deploy` command on those metadata, without involving SGD. 
Or, as @scolladon suggested, if you use the `-d (--generate-delta)` option in SGD, you could also add the additional files to deploy to SGD's output before performing the deployment.

**Comment by scolladon** [comment]
Hi @mateuszzw !

I think this [PR](https://github.com/scolladon/sfdx-git-delta/pull/210) got you covered 😉 

Using the new parameters it introduces you can now [explicitly include specific files for inclusion or destruction regardless of diff](https://github.com/scolladon/sfdx-git-delta#explicitly-including-specific-files-for-inclusion-or-destruction-regardless-of-diff)

Reopen this issue if you have anything to raise !

**Comment by danielperrella** [comment]
Hi @scolladon 
I am trying to use this command as I have the profiles in the .gitignore, retrieve them at deployment from the source environment, clean them up and would like to add them to the deployment file.

I created an .include file, where I put the relative path to the profile, for example:
force-app\main\default\profiles\Admin.profile-meta.xml

And I run the command:
sfdx sgd:source:delta --to feature/test --from main --include .include --output . --loglevel debug  
but the package/package.xml does not present the profile, is there something I am doing wrong or is it formally correct?

**Comment by scolladon** [comment]
Hi @danielperrella,

It is formally correct and you are doing nothing wrong.

The plug-in uses the repository content to create the package.xml (and copy the files using `-d`).

This means copying the files in the repo without committing them will not make the plug-in detect them.

Right now I can think of 2 ways to deal with this situation (maybe there are more):
- In the CI/CD context, force add the profiles and commit them, then run sgd. Do not push this commit, it will be forgot when the CI/CD container will be deleted at the end of its execution. This hack is a bit dirty.
- Run sgd and then add the profiles in the package.xml using sed or your favorite xml file tool.

I hope it helps, let us know how you will solve this, it may help others as well 😁
