### ISSUE TITLE
"error": "--from is not a valid sha pointer: 'DEV'",

### ISSUE THREAD

**Issue by sbsousa** [scolladon/sfdx-git-delta#282]
Deltas in my Azure DevOps pipeline stopped working following the release to 5.1.0 this morning. The release notes show a new feature release
**verify --from and --to parameters to be valid git pointer** 

I am now receiving ""error": "--from is not a valid sha pointer: 'DEV'" when running the following command:

sfdx sgd:source:delta --to HEAD --from DEV --ignore .forceignore --output ./delta/ --generate-delta

I am able to run the command manually from CLI but not within the CI/CD pipeline.

**Comment by scolladon-sfdc** [comment]
Hi @jdgirald !

Thanks for raising this issue and sorry for the inconvenience here.

I think the branches are not created in the CI/CD you need to manually refer to them via the remote
Could you try in the CI/CD to specify the remote ?
```bash
$ sfdx sgd:source:delta --to "HEAD" --from "origin/DEV" --ignore .forceignore --output ./delta/ --generate-delta
```

@mehdisfdc if this is the root cause, lets consider improving the readme for the CI/CD use case, we had a [similar issue](https://github.com/scolladon/sfdx-git-delta/issues/275) with github action

**Comment by sbsousa** [comment]
@scolladon Confirmed working with "origin/Dev". Thank you!

**Comment by scolladon** [comment]
Hi! New release [5.1.1](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.1.1) as just been shipped with the fix for the tag usage with `--to` and `--from` parameters
We also added a [section to explain a little bit how to use it in CI/CD context](https://github.com/scolladon/sfdx-git-delta#cicd-specificity)
