### ISSUE TITLE
Custom labels not in package.xml

### ISSUE THREAD

**Issue by kusalgrg** [scolladon/sfdx-git-delta#284]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

We're getting deployment error when deploying generated delta changes that includes custom label change.

The generated delta change has the custom label file and also includes the modified custom label in the package.xml. However, when changes are deployed to the target org, we are getting the error below where it's expecting all custom labels to be in the package.xml. 

Example of deployment error: 
labels/CustomLabels.labels (Custom Label) Not in package.xml

### What is the parameter and the value you used with it?

sgd:source:delta --to HEAD --from targetBranch --source projectDir  --api-version apiVersion  --output outputDir / --generate-delta

### What is the expected result?

Deployment to succeed without the custom label error. 

### What is the actual result?

Deployment fails with error - labels/CustomLabels.labels (Custom Label) Not in package.xml

It's expecting all custom labels to be included in the package.xml

package.xml includes only the modified custom label. 
 
    <types>
        <members>Changed Custom Label</members>
        <name>CustomLabel</name>
    </types>

## Steps to reproduce

- Modify custom label
- Generate the delta changes 
- sgd:source:delta --to HEAD --from targetBranch --source projectDir  --api-version apiVersion  --output outputDir / --generate-delta
- Deploy the generated delta change 

---

## Execution context

---

**Operating System:** Windows 2012 Server 

**yarn version:** …

**node version:** …

**git version:** 2.18.0.windows.1

**sfdx version:** sfdx-cli/7.144.2 win32-x64 node-v16.14.2

**sgd plugin version:** sfdx-git-delta 5.1.2

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @kusalgrg !

Thanks for raising this issue and for your interest in the plugin.
Sorry for the inconvenience.

I found a similar [issue](https://github.com/forcedotcom/cli/issues/41) in the sfdx CLI itself.
It seems to have been fixed in the past, maybe this is a regression.
Per your remarks and those information it does not seems to be an issue from the plugin itself.
Let's investigate on that anyway.

In the meantime they are suggesting to change the type in the package.xml using `CustomLabels` instead of `CustomLabel`.
Not sure if it will unblock you as it seems to deploy every `CustomLabel` from the sources.

How are you deploying currently ? Using `-x` (from package.xml using sources from your src) or using `-p` (from the incremental generated sources in the output folder) ?

**Comment by kusalgrg** [comment]
Hi @scolladon 

Thank you for checking on the issue. 

In our CICD pipeline, to deploy we use the 'force:mdapi:deploy' command after converting source to mdapi format. 

The workaround for this issue would be to deploy all custom labels by modifying the package.xml. Currently, when deploying only the delta changes we use the generated package.xml file so therefore we would need to add some custom code to modify the contents of the package.xml file.

**Comment by scolladon** [comment]
I'm curious, is there a reason why not using `force:source:deploy` (`-x` or `-p`) ?
I'm asking this because maybe it will work using this command (we do not have issue reported yet on those one)

**Comment by scolladon** [comment]
Ok great, let us know the result, I'm curious

**Comment by kusalgrg** [comment]
Hi @scolladon, Issue is not encountered when using `force:source:deploy` command. We have a workaround in place for this issue. I think we can close this issue. Thanks for your help.
