### ISSUE TITLE
--generate-delta (-d) parameter cannot be used when --to (-t) parameter is not equivalent to HEAD

### ISSUE THREAD

**Issue by ronika-das** [scolladon/sfdx-git-delta#354]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?
Yes

## What is the problem?

I am trying to update the sfdx-git-delta by installing version 5.0.0. Current version being used is 4.7.0.
This is resulting in below error : "--generate-delta (-d) parameter cannot be used when --to (-t) parameter is not equivalent to HEAD". I have not changed any scripts etc. I am just trying to update a newer version of the plugin

### What is the parameter and the value you used with it?

sgd --to f524171b34364b64c124e963a88cdea3f6d977f9 --from 0367c96a67b2a49d2410837bc39e8439563ff8ee --repo . --output ./build -d .

->Here I am passing the commit SHA values between which I need the files. The output should be save inside the build folder.

### What is the expected result?
Files that were updated b/w the two commits should be available inside the build/force-app folder.

### What is the actual result?

sgd command is throwing the error --generate-delta (-d) parameter cannot be used when --to (-t) parameter is not equivalent to HEAD

## Steps to reproduce

As it is a private repo, I will not be able to provide the repo link.

Install NPM package
npm install sfdx-git-delta@5.0.0 --global

Run the below command
sgd --to $targetSha --from $sourceSha --repo . --output ./build -d . 
->where $targetSha and $sourceSha are two custom SHA, not pointing to HEAD

## Execution context

Operating System: Linux

yarn version: N/A

node version: v16.16.0

git version: 2.17.1

sfdx version: sfdx-cli/7.163.0 linux-x64 node-v16.16.0

sgd plugin version: 5.0.0

## More information (optional)

  Provide the output of these commands:

  $ git diff --name-status --no-renames <from> <to>
Output=
M	.gitlab-ci.yml
M	devopsscript/mrValidation.ps1
M	force-app/main/default/classes/svreRuleKeyGen_Test.cls

  $ git diff --no-prefix 0367c96a67b2a49d2410837bc39e8439563ff8ee 0f93c2709dad92b9e7329d64843b7cd43d38bb2e  -- force-app/main/default

Output =
--- force-app/main/default/classes/svreRuleKeyGen_Test.cls
+++ force-app/main/default/classes/svreRuleKeyGen_Test.cls

*I apologise in advance in case this is a repeat issue. I could not find in the Issues

**Comment by scolladon** [comment]
Hi @ronika-das !

Be careful, the version [5.0.0 decomissionate the sgd CLI](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.0.0)
It means you need to use it as an sfdx plugin starting version 5.0.0.

The error encountered here is expected.
This is a behaviour introduced by the #243 ([here](https://github.com/scolladon/sfdx-git-delta/pull/234/files#diff-7f73a85f9d0c5fe972f860e3ba6bab51bcff0788e771327b3047a0e9aabd6b95R59)) included in the release 5.0.0.

We included this because when `-t` is different than `HEAD` (current state of the repository) it means we would need to copy, into the output folder, the file version from the `-t` repository state instead of the one in HEAD. We are currently copying file from the file system and not from git. It would require playing with `git show $REV:$FILE` and pipe it to the output folder which is way more complicated than what we are currently doing.

We found there is not much usage doing `-d` from another commit than HEAD so we decided to just block this failing usage.
You are currently the first raising your hands for this particular usage.
I'm curious, why are you using it from a different commit than HEAD ? What is your use case ?
Do you think we should go for the `git show $REV:$FILE` solution and not block `-d` when `-t` is not HEAD ?

**Comment by ronika-das** [comment]
Hi @scolladon 

Thank you sharing.
We have two use cases for the --to parameter to have a value different than HEAD.

1. Our dev team raises Merge requests using cherry pick option. We have enabled Merge request pipelines where we try to validate the differences b/w two commits such that only the changes raised in the Merge Request are validated. So sometimes the target commit is not the HEAD in this case

2. We have pipelines for Dev and UAT. We want the Dev pipeline to be successful and only then the UAT pipelines should pick the changes(which has passed in Dev)
For dev pipelines, the changes are picked from last successful **Dev tag to HEAD**. (all good here)
For UAT pipelines, the changes are picked from **last successful UAT tag to last successful Dev Tag**. For our UAT pipelines, the  **--t** parameter will not be HEAD.

It would be great if you could keep the older versions active for some time :)
And yes if would be really great if we not block -d when -t is not head.

Happy to connect with you incase you want more details.

**Comment by scolladon** [comment]
Thanks for sharing those very nice insight @ronika-das 

We are not destroying any version for now (and we don't plan to) so you will still have v4.*.*
We are just not maintaining the sgd CLI (V4 and below).
If you want to keep using sgd CLI instead of `sfdx` you can still use latest v4, you will not have the issue 

I have created an enhancement request (#355) to track this.
We can discuss there and you'll be updated of the progress in this new enhancement request (no ETA for now)

In the mean time, can we close this issue as there is an explanation, a workaround(ish) and a feature in the backlog ?

**Comment by ronika-das** [comment]
@scolladon  Yes sure.
We can close this issue. I will monitor the enhancement request.
Thanks for the opening the enhancement request and keeping the sgd CLI older versions. Really appreciate it
:)
