### ISSUE TITLE
.forceignore failing to exclude "Translations" (latest working version: v5.3.1) 

### ISSUE THREAD

**Issue by patrykzak** [scolladon/sfdx-git-delta#359]
I observed today that translations are coming back to generated package.xml even though they are mentioned in .forceignore file, I have installed previous version v5.3.1 and in that version it's working as expected.
Kindly please fix that issue, maybe there are more metadata, but I only encountered this one

**Comment by scolladon** [comment]
Hi @patrykzak 

Thanks for raising this issue and helping improving the plugin.

I think this issue maybe related to this recent enhancement #321 
This change allow to add the translation when there is a translation for a flow and a flow has been modified.
Because if not pushing the translation at the same time of the flow it seems to remove previous translations.

Does your changes includes translations ?

**Comment by patrykzak** [comment]
@scolladon thanks for quick response, what you stated in your message is correct.
I have translations changes in my pull request, I use -i .forceignore where I specify that translations should be ignored, however generated package still contains translations.

**Comment by mehdisfdc** [comment]
Hi! 

This is something we discussed with @scolladon today, and I agree with you @patrykzak: since you explicitly ignored the translations through the ignore file, it should **not** be part of the SGD output.

The new feature to add automatically the translations when there is a change in a related flow (https://github.com/scolladon/sfdx-git-delta/pull/322) is a great **default** behaviour. But when it conflicts with the content of the ignore files, the latter should win.

Stay tuned for a fix in the next version :-)

**Comment by scolladon** [comment]
We just released the version 5.5.1 @patrykzak with this fix
You can install it using the `latest-rc` tag:
```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
```

Let us know if everything is working following the expectations, we will make it the `latest`
