### ISSUE TITLE
.sgdignore does not accept path exclusion, like !

### ISSUE THREAD

**Issue by AllanOricil** [scolladon/sfdx-git-delta#386]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

I tried to "exclude all but some" and verified it does not work. In my .sgdignore file I had the following paths:

````
dir
!dir/dir
````

I this case Im expecting sgd to exclude all metadata changes from `dir` but the ones under `dir/dir` 

### What is the parameter and the value you used with it?

`sfdx sgd:source:delta -f <GIT_REF> -o <OUTPUT_FOLDER> -i <PATH_TO_SGDIGNORE>`

### What is the expected result?

.sgdingore must exclude all metadata changes from `dir` but the ones under `dir/dir` 

### What is the actual result?

.sgdingore with paths exclusions isn't working

## Steps to reproduce

---

1 - create a .sgdignore with that allows all files under a directory but exclude few using `!`

````
force/main/default/lwc
!force/main/default/lwc/cs_*
````

2 - run `sfdx sgd:source:delta -f <GIT_REF> -o <OUTPUT_FOLDER> -i <PATH_TO_SGDIGNORE>`
3 - verify that all lwc are included, and not just the ones prefixed with `cs_*`

## Execution context

---

![image](https://user-images.githubusercontent.com/55927613/200532962-152d8a21-79a3-4ef1-b1ff-5ba78e4979ad.png)

**Comment by scolladon** [comment]
Hi @AllanOricil 

Thanks for raising this issue and to help the plugin getting better.
We fixed an issue (#385) introduced in v5.6.0 related to ignore 

Could you try with the v5.7.0 (actual latest) and tell us if you still have this behavior in your use case ?

**Comment by scolladon** [comment]
Hi @AllanOricil 

I tried locally with the version v5.7.0 (current latest) and was able to reproduce this behavior.
Then I looked at our implementation compared to what is recommended by the [ignore library](https://github.com/kaelzhang/node-ignore) we are using and saw nothing wrong.
I wrote a quick swap of the implementation using `test` instead of `ignore` and I had the same result.

Then I saw in there [usage](https://github.com/kaelzhang/node-ignore#usage) that their are ignoring the content of a folder and not folder itself. Then I saw in the example here that this is not what is done in this example.

So I tried a few things with the v5.7.0:
-	❌ exclude the folder and include some of the content: 
```
force/main/default/lwc
!force/main/default/lwc/cs_*
```
=> `cs_*` files are excluded

- ❌ swap them
```
!force/main/default/lwc/cs_*
force/main/default/lwc
```
=> `cs_*` files are excluded

-	✅ exclude the folder **content** and include some of the content: 
```
force/main/default/lwc/*
!force/main/default/lwc/cs_*
```
=> `cs_*` files are included !!

- ❌ swap them
```
!force/main/default/lwc/cs_*
force/main/default/lwc
```
=> `cs_*` files are excluded (normal the inclusion rule is after the exclusion so it is ignored)

Let us know if you are able to make it works as well on your side and if we can close this issue

**Comment by 1ktribble** [comment]
We're experiencing similar issues with the .sgdignore file and its detection of destructive changes. We've added some file paths in our .ignore file, and it's still showing up in destructiveChanges.xml.

Command running:
`sfdx sgd:source:delta --to "$compareTo" --from "$compareFrom" --repo . --output . --ignore .sgdignore --source force-app`

.sgdignore file:

```
force-app/main/default/objects/Custom_Object__c/*
```

destructiveChanges.xml...
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Custom_Object__c.Custom_Field__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>Custom_Object__c</members>
        <name>CustomObject</name>
    </types>
    <version>53.0</version>
</Package>
```

This has worked in the past.

**Comment by scolladon** [comment]
Hi @1ktribble 

What is the version you are currently using ?
There was a similar issue (#383) introduced in v5.6.0 and solved in v5.7.0.

**Comment by 1ktribble** [comment]
> Hi @1ktribble
> 
> What is the version you are currently using ? There was a similar issue (#383) introduced in v5.6.0 and solved in v5.7.0.

5.7.0

**Comment by scolladon** [comment]
Hi @1ktribble

I think I see what is the issue for you.
As you are using only `-i` and not `-D` the ignore should be applied to both changes and deletions.
When [both are used in conjunction](https://github.com/scolladon/sfdx-git-delta#exclude-some-metadata-only-from-destructivechangesxml) the file passed to `-i` is not used for deletion, instead the files passed to `-D` is used.

That is definitely a remaining issue (a regression) introduced in v5.6.0 as well as #383.

I'll work on that soon and let you know

**Comment by scolladon** [comment]
@AllanOricil have you been able to fix your situation by using `force/main/default/lwc/*` instead of `force/main/default/lwc`?

**Comment by AllanOricil** [comment]
Everything is fine. Thank you for the quick replies.

**Comment by scolladon** [comment]
@1ktribble release `v5.7.1` is available ! Under channel `latest-rc``

You can install it with the following command:
```sh
$ sfdx plugins:install sfdx-git-delta@latest-rc
```

You could try on your side and let us know the result please ?
It will help us to promote it as latest
