### ISSUE TITLE
Add predefined metadata to every package.xml that sgd creates

### ISSUE THREAD

**Issue by AllanOricil** [scolladon/sfdx-git-delta#389]
### Is your proposal related to a problem?

nope

---

### Describe a solution you propose

Im building few metadata at build time, in the pipeline, and I would like to have them listed in the package.xml so that they get deployed. Since I'm not versioning these components, I don't really want to commit them.

---

### Describe alternatives you've considered
I could make make my workflow add commits, but I dont want to do that as Im not versioning these metadata.

---

### Additional context

---

![image](https://user-images.githubusercontent.com/55927613/201131553-9f39a905-32e8-4c5f-97e6-cc9c499ba816.png)

**Comment by AllanOricil** [comment]
@scolladon I noticed that this has already been implemented. I can use the -n flag and pass a file to it. But it is not working


````
sfdx sgd:source:delta -f origin/main -o dist/*** -i .sgdignore -n .sgdinclude
````

this is my `.sgdinclude` file

````
salesforce_sfdx/main/default/lwc/env
salesforce_sfdx/main/default/customMetadata/ENV.*
````

I was expecting to see that lwc called `env` and all custom metadata called `ENV.*` in the package.xml. This is the resulting package.xml


````xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>ENV__mdt.Value__c</members>
        <name>CustomField</name>
    </types>
    <types>
        <members>ENV__mdt</members>
        <name>CustomObject</name>
    </types>
    <types>
        <members>COM_BillingAccountsCalloutService</members>
        <members>COM_DokobitCalloutService</members>
        <members>COM_InvoiceCalloutService</members>
        <members>COM_PaymentRefundCalloutService</members>
        <members>CUS_AskurOrdersCalloutService</members>
        <members>CUS_ProductDiscountCalloutService</members>
        <members>DSP_DocumentSigningReqCalloutService</members>
        <members>ENV</members>
        <members>ENVTest</members>
        <name>ApexClass</name>
    </types>
    <version>55.0</version>
</Package>

````

**Comment by AllanOricil** [comment]
I have also tried a .sgdinclude with

````
**/lwc/env
**/customMetadata/ENV.*
````

````
**/lwc/env/
**/customMetadata/ENV.*
````

````
**/lwc/env/*
**/customMetadata/ENV.*
````

and none of them added the lwc or the cusotm metadata entries to my package.xml

**Comment by AllanOricil** [comment]
The only thing that worked for me was adding a dummy commit before computing the package.xml

![image](https://user-images.githubusercontent.com/55927613/201138313-6f248709-9b54-40f4-be56-23c0ba92f41f.png)


![image](https://user-images.githubusercontent.com/55927613/201138355-8622605b-7b3f-4eb0-bb7e-d3a78fb5c633.png)

**Comment by scolladon** [comment]
Hi @AllanOricil 

Thanks for proposing this enhancement.
You are right with your exploration.

The actual solution using `--include` or `--include-destructive` works for already committed files.
There is an ongoing PR that will make it more related to the `--to` commit repo state, so it will be not possible to ask for element present in HEAD but not present in `--to`.

We did not want to add a feature to add additional files not tracked in the repo because the plugin deal with the repo content, considering it as the source of truth. And we think it is doable with other tools as well

If you need to have additional content not in the repo, I would do that the following way:
1. Have a package.xml on the side with the element I want to always add (let's name it complementary package)
2. Have a folder with those metadata (let's name it complementary content)
3. Generate incremental package deployment using sgd plugin (with `-d` if incremental content is wanted)
4. [Merge](https://github.com/scolladon/sfdc-merge-package) generated package.xml with the complementary one 
5. Copy complementary content in the incremental content (be careful of the potential overrides though) (`cp -na complementary/. output/` something like that)

I hope it helps you
Let us know if you have a specific idea of feature around this topic.
Maybe we could design together a set of commands here to do what you want (like the steps shown above) and detail that process in the [advance usage](https://github.com/scolladon/sfdx-git-delta#advanced-use-cases) section of the README

**Comment by AllanOricil** [comment]
Nice! I also thought about creating my own package.xml merge tool. Cool that you have already done that. Will explore it.

**Comment by mehdisfdc** [comment]
If that's ok with you @AllanOricil and @scolladon I suggested to close this issue, as:
- SGD is focused what's committed in the repo
- Workarounds can be implemented outside of SGD
- I'm not sure that is the actual use-case behind that enhancement request, but if we're talking about managing environment-specific metadata, there is now a better for that in the Salesforce CLI: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_string_replace.htm
