### ISSUE TITLE
Exclude "Renamed" from the package.xml

### ISSUE THREAD

**Issue by AllanOricil** [scolladon/sfdx-git-delta#418]
### Is your proposal related to a problem?

We were working on a mono repo with single package. Now we broke our metadata into multiple packages, sgd is adding "renamed" items to the package.xml when comparing our latest release tag with HEAD. There is no problem with that because we will only end up redeploying everything to Production, but it is not ideal as it takes more time for validating everything again including non changed metadata, and I believe it will also show up as a "change" in the org, even if the file has not changed at all.

### Describe a solution you propose

Maybe you can add a optional flag like `--ignore-renamed`

### Describe alternatives you've considered

I will just redeploy everything to production, including the metadata that did not change.

### Additional context

N/A

**Comment by AllanOricil** [comment]
It can be done with a filter https://stackoverflow.com/questions/6894322/how-to-make-git-diff-and-git-log-ignore-new-and-deleted-files

**Comment by AllanOricil** [comment]
@scolladon can I simply change this file https://github.com/scolladon/sfdx-git-delta/blob/main/src/utils/fileGitDiff.js to exclude "renames" ? or is there somehwere else I need to change?

**Comment by AllanOricil** [comment]
My idea is to run `git --no-pager diff from..to --diff-filter=R ` and subtract this answer from the final list when `--ignore-renamed` is true, before creating this set https://github.com/scolladon/sfdx-git-delta/blob/09405d3d040f8f27dc9e8306d103cc6893283929/src/utils/repoGitDiff.js#L57
What do you think?

**Comment by scolladon** [comment]
Hi @AllanOricil!

Thanks for this detail enhancement request.

Under the hood this is what is done by the plugin, we use `--diff-filter`.
We use it with `--no-renames` parameter so renamed files are converted into Added and Deleted lines.

We already have implemented a logic to filter out moved element from the deleted elements so they are not added as well in the `destructiveChanges.xml`

It is important because git detects rename file name as well as file moved.
And we don't want to ignore file renamed.
Renamed files new name needs to be listed in the `package.xml` and in their old name needs to be listed in the `destructiveChanges.xml`

Your suggestion is to ignore file moved from the `package.xml` as well (not only the `destructiveChanges.xml`): 
- same file
- same name
- different location
Right ?

If so, I think wee could improve `_treatResult` method to not keep added files that are also deleted
I'm not sure if we should do it everytime, I'm not sure metadata are impacted by their location in the source repository (maybe)

What do you think guys?

**Comment by AllanOricil** [comment]
This wouldn't work. While moving files from one package to another we must redeploy everything so that the Org becomes aware that those metadata now lives in a different package/folder. If we don't do it, a n "UNKNOWN_EXCEPTION" appears while deploying/validating changes because SF treats it as a duplicate metadata

![image](https://user-images.githubusercontent.com/55927613/211833592-656a7d52-b34c-480e-b058-d024ff2555f1.png)
