### ISSUE TITLE
error output must be added to stdout when using --json

### ISSUE THREAD

**Issue by AllanOricil** [scolladon/sfdx-git-delta#568]
### Is your proposal related to a problem?

every other sfdx command send error messages to stdout when using --json, but sgd does not

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/55927613/231499387-e9b06cb5-db7d-4e04-9060-40c5356b4fd9.png">

edit: I noticed that there is a warning message in the error key, instead of being in the warnings array. I think this is confusing.

### Actual Output

````json
{
    "status" : 1,
    "result" : null
}
````

### Expected Output
````json
{
    "status" : 1,
    "result" : {
        "success": false,
        "error": "error message"
        "warnings": [],
        "output":  <OUTPUT_DIR>
    }
}
````

**Comment by scolladon** [comment]
Hi @AllanOricil !

Thanks for this enhancement and thanks for contributing in making this project better!

I think it is somehow related to this [enhancement](https://github.com/scolladon/sfdx-git-delta/issues/378) as well.

I do not know how we will treat this as a whole, but we definitely need to be compliant with the standard sfdx output behavior (which is not the case currently).
The issue we have is we cannot introduce breaking change because current usage is based on the actual behavior.
We need to be careful when addressing this.

One way I was thinking about was to deal with this behavior compliance when migrating to `sf` and leave the `sfdx` plugin behavior as it is currently. It will be easier to introduce new behavior at that time.

For the warning in the error attribute, that is a very good point, nice catch, I'll try to work on that soon.
Just to be sure, in order to reproduce I have to create a tag having the same name as a branch, and pass that refname to the `--from` parameter so `git` get confused ?

**Comment by AllanOricil** [comment]
@scolladon this git warning message is displayed when you try to fetch a ref from remote and map it to a local ref that already exists, for instance:

````
git fetch origin +HEAD:HEAD
````
<img width="358" alt="image" src="https://user-images.githubusercontent.com/55927613/232577887-2d9a605e-9597-4eda-9c29-e9f5b4f83b5c.png">

<img width="871" alt="image" src="https://user-images.githubusercontent.com/55927613/232577452-8ce6563b-3d9b-40d9-80bc-9098941cf51d.png">

**Comment by AllanOricil** [comment]
@scolladon this error happens because Im using a single command to fetch both "from" and "to" at the same time.

`git fetch origin +$git_ref_from:$git_ref_from +$git_ref_to:$git_ref_to"`

when `git_ref_to` is empty, I set it to HEAD, then this happens

<img width="889" alt="image" src="https://user-images.githubusercontent.com/55927613/232901636-20b0212f-1d31-42ef-b28e-3cbd2cb1d8aa.png">

I did this way to avoid having to treat tags and branches differently, and to fetch exactly only what is necessary for SGD to compute the diffs

**Comment by AllanOricil** [comment]
by the way, never try to fetch HEAD into a local HEAD ref. This breaks git, and you will have to delete the local branch

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/55927613/232903248-f0011559-f924-4549-bd62-f13affef2905.png">
