### ISSUE TITLE
Error -  "API version not found or not supported, using '57' instead"

### ISSUE THREAD

**Issue by AnantSahTeli** [scolladon/sfdx-git-delta#641]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?

---

When running delts sgd, throwing error, if the api version is greater than 57

### What is the parameter and the value you used with it?

```sh
sfdx sgd:source:delta --from "HEAD~1" --to "HEAD" --repo . --output . --source "env_spec_config/sfqa/force-app"
```

### What is the expected result?

Generate delta package.xml using sourceapiversion 58.0

### What is the actual result?

Error:
(node:29048) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": [
    "API version not found or not supported, using '57' instead"
  ]
}

## Steps to reproduce

Update sfdx-project.json file with "sourceApiVersion": "58.0" and run a sgd command for delta

## Execution context

$ uname -v ; yarn -v ; node -v ; git --version ; sfdx --version ; sfdx plugins
-->

**Operating System:** … Linux

**yarn version:** …

**node version:** …17.6.0

**git version:** …

**sfdx version:** …7.204.6

**sgd plugin version:** …5.19

## More information (optional)

sfdx sgd:source:delta --from "HEAD~1" --to "HEAD" --repo . --output . --source "env_spec_config/sfqa/force-app"
(node:20428) Warning: Deprecated config name: apiVersion. Please use org-api-version instead.
(Use `node --trace-warnings ...` to show where the warning was created)
{
  "error": null,
  "output": ".",
  "success": true,
  "warnings": [
    "API version not found or not supported, using '57' instead"
  ]
}

**Comment by scolladon** [comment]
Hi @AnantSahTeli !

Thanks for raising this issue and thanks for contributing in making this project better!

What I understand is you would like to use the version `58`, right ?
And what I see is the plugin version used to generate this issue is `5.19.0`, right ?

If those are right then could you update the plugin to use the `latest` version (by either executing `sfdx plugins:update` or `sfdx plugins:install sfdx-git-delta@latest` and try again please ? We shipped the `v58` metadata API support in the [`v5.22.0`](https://github.com/scolladon/sfdx-git-delta/releases/tag/v5.22.0)

Let us know if it helped

**Comment by AnantSahTeli** [comment]
Thanks a lot @scolladon It worked.

**Comment by AnantSahTeli** [comment]
Hi @scolladon,

we are seeing the same issue again when going to use api version 59. My current plugin version is 5.25.2.

Do you see if this supported or any new version is to be released to support api version 59?
