### ISSUE TITLE
Detect metadata type based on file extension instead of directory

### ISSUE THREAD

**Issue by jjulicher** [scolladon/sfdx-git-delta#642]
### Is your proposal related to a problem?

Metadata is not picked up and handling is too opaque. I had an issue where my directory name for PlatformEventSubscriberConfigs had a lower-case P at the start e.g. platformEventSubscriberConfigs. SFDX handles this fine but sgd does not. 

I was also experimenting with putting my test classes in a test directory. But this resulted in sgd not picking up changes to those files. 

---

### Describe a solution you propose

Ignore the directory structure when examining changes and if there is change that is not matched to metadata within project directories they should be output as a warning in the output. 

---

If a change is detected only the extension is used to identify the metadata type. 

### Describe alternatives you've considered

---

none.

### Additional context

---

**Comment by scolladon** [comment]
Hi @jjulicher !

Thanks for raising this issue and thanks for contributing in making this project better!

We had this kind of request previously and we tracked this requirement in this github [issue](https://github.com/scolladon/sfdx-git-delta/issues/352).
The change is not trivial for a usage that is not following the metadata specification, with a certain amount of corner cases to handle.

Let's keep it open and see if there are other people interested !

**Comment by jjulicher** [comment]
I wouldn't say how you store your metadata files locally forms part of the specification. It only specifies how the metadata is 'sent' to the API within the zip file.  It's irrelevant to the API specification how you store it locally - it's just a convention to store it the same as the metadata API. 

However I understand it's not trivial as you didn't separate that out early in the project. I might have a stab at it in the meantime.

**Comment by scolladon** [comment]
I'll take the design from where we left it previously.
There are multiple corner cases with the sources and not every kind can be detected from their file extension only.
I have a couple of ideas to experiment.
Thanks @jjulicher for reigniting the topic, it gives me a ton of energy ! Would you be ok to participate the code review and the QA ?

**Comment by jjulicher** [comment]
Hi Sebastian

Yeah I'll participate. Been a while since I last did a lot of js dev.

cheers

**Comment by jverelst** [comment]
@scolladon @jjulicher we are running into the same issue here, and our deployment pipeline is relying heavily on diffs. We recently moved from the obsolete `sfpowerkit` diff to `sgd`, but we now run into exactly this issue. Actually we run into 2 issues:
- classes that are located in `/src/main/test/` are not being identified as classes
- classes that are located in `/src/main/dlrs/triggers/classes/` are mis-identified as triggers, because "triggers" comes before "classes" in the path.

I can give it a go to create a PR, my javascript/typescript skills are a bit rusty, but maybe I can provide something you can improve upon?

My approach would be to make it a 2-step check:
- First see if you can match based on extension (and also take into account that only the -meta.xml file might be changed)
- If that fails (for instance for LightningComponentBundles), use the same approach as currently, but with the path elements in reversed order to give the last path element the most prevalence.

**Comment by scolladon** [comment]
Hi @jverelst,

Thanks for this very clear explanation.

First I think you could benefit from `sgd` without having the suggested feature (in the mean time).
To do so you need to restructure the repository a bit.
- classes located in `/src/main/test/` could be moved in `/src/main/test/classes/` or `/src/main/classes/test/`
- classes located in `/src/main/dlrs/triggers/classes/` could into another folder instead of `triggers`

In the meantime, I propose to start a feature branch and work on it.
I propose I do a first draft of this feature, following your approach @jverelst 
And maybe you (@jverelst) and @jjulicher can review the code and help with the testing?

**Comment by jverelst** [comment]
@scolladon wow, what a lightning-fast reply :-). Indeed for now we will do exactly that, moving the classes to those directories, but a permanent fix would be greatly appreciated.

Happy to help with reviewing and testing! We have a lot of edge-case commits in our repo, so I can probably generate a lot of diffs and see if the new code handles them as expected.

**Comment by jverelst** [comment]
Hi @scolladon, I was wondering if you've made progress on this issue yet? We are looking forward to the fix :-)

**Comment by scolladon** [comment]
Hi @jverelst !

I'll start spiking on that beginning of 2024.
It is the next big feature we want to ship!

Stay tuned!
