### ISSUE TITLE
TypeError: core_1.Flags.option is not a function

### ISSUE THREAD

**Issue by jonny-harte** [scolladon/sfdx-git-delta#660]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
I've started getting the below error when running on my local machine. CI is fine, I haven't made any updates to the scripts in a long time.

### What is the parameter and the value you used with it?
`sfdx sgd:source:delta --loglevel trace --to \"HEAD\" --from $(git rev-list --max-parents=0 HEAD) --output manifest --source force-app --ignore .forceignore`

### What is the expected result?

Manifest of whole repository generated.

### What is the actual result?

TypeError: core_1.Flags.option is not a function

## Steps to reproduce

Attempt to run the script from an npm script.

`"manifest:refresh": "sfdx sgd:source:delta --loglevel trace --to \"HEAD\" --from $(git rev-list --max-parents=0 HEAD) --output manifest --source force-app --ignore .forceignore",`

## Execution context
**Operating System:** macOS 13.4.1
**node version:** v19.3.0
**git version:** git version 2.39.2 (Apple Git-143)
**sfdx version:** sfdx-cli/7.209.6
**sgd plugin version:** 5.24.0

**Comment by scolladon** [comment]
Hi @jonny-harte !

Thanks for raising this issue and thanks for contributing in making this project better!

I do not experience the same issue locally.
Do you think it is reproducible on my machine using a dedicated branch (issue/660) on the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) ? Do you think it could be related to something on your repo that could be isolated ? I'm not sure because it seems to be an issue related to the core plugin framework itself, but we never know.

Have you try to uninstall/reinstall the plugin and/or sfdx-cli ?

**Comment by jonny-harte** [comment]
Thanks @scolladon,

I uninstalled the plugin and moved from sfdx (v7) to sf (v2), then reinstalled the plugin using the below command. Seems to be working again now.

`sf plugins install sfdx-git-delta`

https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm
