### ISSUE TITLE
Intermittent erroneous empty files created in experiences and staticresources folders

### ISSUE THREAD

**Issue by gdman** [scolladon/sfdx-git-delta#661]
We've just started using sfdx-git-delta - great tool, we're looking forward to using it on more projects.

Whilst testing, I found builds fail intermittently where the delta contains experience bundles or static resources. It appears that empty [something]-meta.xml files are created in random places in experiences/ and staticresources/ - these files don't and shouldn't exist.

This only happens on our CI builds (within a Docker container running on Bitbucket Pipelines) - but is reproducible in almost all builds containing these files. Though, I can't reproduce locally on my mac (and I've tried a lot...).

I've investigated the issue and it appears the tool attempts to get -meta.xml files from git that don't exist. I can see why that behaviour would exist - it's common that a static resource would change and therefore be included in the delta but the meta file wouldn't but both files need to be in the deploy. I think that logic could potentially be optimised in the future i.e. I don't think there's a need to check for -meta.xml files within sub folders of staticresources or sub folders of experiences, etc. However, that doesn't explain why the empty files are being created.

On further digging, I've traced the issue to the stream handling of processes - specifically the git show command used to retrieve file contents from the repository. What's happening is - there's an attempt to run git show for the file that doesn't exist but whilst the command is failing, the code is not waiting for that failure and instead proceeds to create the file (that doesn't exist) with no content (because git show correctly doesn't return anything).

In the stream handling there are two issues:
1. The code doesn't wait for the stream to close - it looks like it's attempting to wait for all of stdErr and stdOut but that code doesn't work (or doesn't always work) and that isn't the same as waiting for the stream to close
2. There is no check of the error code returned from the command - not all commands will output to stdErr and commands can output to stdErr without there actually being an error

This is the method in question:

```
const getStreamContent = async stream => {
  const content = []
  for await (const chunk of stream.stdout) {
    content.push(chunk)
  }
  const error = []
  for await (const chunk of stream.stderr) {
    error.push(chunk)
  }
  if (error.length > 0) {
    throw new Error(error.join(''))
  }
  return Buffer.concat(content)
}
```
in src/utils/childProcessUtils.js

Async/await syntax appears to be quite problematic with streams, instead I propose this:

```
const getStreamContent = async stream => {
  return new Promise((resolve, reject) => {
    const content = []
    const error = []

    stream.stdout.on('data', data => {
      content.push(data)
    })

    stream.stderr.setEncoding('utf8')
    stream.stderr.on('data', data => {
      error.push(data.toString())
    })

    stream.on('close', code => {
      if (code != 0) {
        reject(new Error(error.join('')))
      }

      resolve(Buffer.concat(content))
    })
  })
}
```

Listen for data on stdout and stderr as before but only return when the stream has closed. Determine success or failure based on the process error code. And wrap the whole thing in a promise.

This is a like for like replacement of what's already there whilst resolving the bug.

I've applied this fix to our build and no longer see any issues in Bitbucket Pipelines.

I'm committing the changes at the moment and a PR will be raised shortly.

Thanks again for your work on this tool - it's awesome.

**Comment by scolladon** [comment]
Hi @gdman !

Thanks for raising this issue and thanks for contributing in making this project better!

That's a great point you make, this part of the code is very special and you're right it can be improved.
I think we had a previous implementation close to the one you made but I wanted to switch to a simpler way to write the code  in order to decrease the asynchronous part of the implementation. I wanted to make the code less aware of the underlying events and make it more straightforward to read and let javascript deal with asynchronism for us. I introduced a really sneaky bug, you found, by doing so... my mistake, sorry about that

I also agree with you that we could avoid try to copy `-meta.xml` file when we know for sure it should not be there but it is not easy to isolate and to write with the current design.

I plan to swap the current git implementation to use an existing node library and avoid having to deal with spawn and git command ourself.
I also plan to migrate to typescript and try to refactor the current implementation to follow hexagonal architecture best practices. This will be the occasion to take of the copy of `-meta-xml` file when we should not.
Lot of work under my plate and so less time.
I'll do my best.

Great analysis and great value here, thank you so much, I can't wait for the PR
I really appreciate all the hard work you made to have this level of understanding and to come with an already working solution. 👏 
Thank you very much

**Comment by scolladon** [comment]
Hi @gdman !

We have [improved the way the file](https://github.com/scolladon/sfdx-git-delta/commit/dd6eca650af02e557643a18f8a72eaf5cb4f5f8a) are copied.
Now the file should not be attempted to be copied multiple times and it should not attempt to copy file that does not exist (either by name or location).

This is going to be released soon.

Thanks for your feedback and for your analysis, it helped us a lot !

**Comment by gdman** [comment]
> Hi @gdman !
> 
> We have [improved the way the file](https://github.com/scolladon/sfdx-git-delta/commit/dd6eca650af02e557643a18f8a72eaf5cb4f5f8a) are copied. Now the file should not be attempted to be copied multiple times and it should not attempt to copy file that does not exist (either by name or location).
> 
> This is going to be released soon.
> 
> Thanks for your feedback and for your analysis, it helped us a lot !

Thanks for the update, sounds awesome!
