### ISSUE TITLE
Changed export from default to named

### ISSUE THREAD

**Issue by pawel-id** [scolladon/sfdx-git-delta#701]
We are using this tool as an imported module in our deployment tool. It works perfectly. Unfortunately we noticed that along with the latest v5.26.0 some breaking change has been introduced. Previously (i.e. v5.25.2 and older) the main function was exported as a default export. Then in order to consume the following code was required:

```javascript
const sgd = require('sfdx-git-delta')
await sgd({params})
```

That way is still in [readme](https://github.com/scolladon/sfdx-git-delta/tree/v5.26.0#use-the-module-in-your-own-node-application), however the behaviour has changed to named export, and now it requires:

```javascript
const { sgd } = require('sfdx-git-delta')
await sgd({params})
```

It would be great to follow semantic versioning rules and not to introduce breaking changes with minor changes. In other words please keep default export when doing minor version bumps.

**Comment by scolladon** [comment]
Hi @pawel-id !

Thanks for raising this issue and thanks for contributing in making this project better!

Yep you're right, it is a breaking change in a minor version without communication.
It is breaking the semantic versioning rules and is a regression.
This bug is not wanted from our side, it comes from our migration to typescript big refactoring.

Here are how we suggest to deal with that:
1. keep it this way, update the readme and the release note for `v.5.26.0`
1. come back to the previous behavior (wich would be a breaking change introduced into a minor version but maybe it is ok as it fixes the bug)

What would be your preferred solution? 1 or 2?
![image](https://github.com/scolladon/sfdx-git-delta/assets/522422/598fb712-3161-46f4-8a40-4ae56a8662fc)

**Comment by pawel-id** [comment]
It happens. I would treat it as a bug and restore previous behavior, then release v5.26.1. From semantic versioning point of view this is proper way to fix.

**Comment by scolladon** [comment]
Option 2 it is !
Welcome to the matrix

**Comment by pawel-id** [comment]
It seems typescript clause `export default someting` is translated into `exports.default = sgd;` which is somehow different that expected `module.exports = sgd`. Then having this approach in order to import this we need to do some extra work:

```
const sgd = require('module').default
```

or 

```
import sgdDefault from 'module'
const sgd = sgdDefault.default
```
