### ISSUE TITLE
Custom Permission metadata not detected

### ISSUE THREAD

**Issue by trudzki-al** [scolladon/sfdx-git-delta#713]
When trying to identify delta between two branches there is missing metadata directory. 
Target branch doesn't contain `force-app/main/default/customPermission` directory while source branch has (including one metadata xml file). 
Calling sgd delta between those branches doesn't include customPermission directory in output directory neither in delta force-app 
 directory nor in destructive changes.

Executed script:
sfdx sgd:source:delta --to "feature/FEAT-123" --from "main" --output "delta/" --generate-delta --source "force-app/" --loglevel=INFO

### What is the expected result?
All metadata differences between branches are included in files created in output directory. 

### What is the actual result?
The `customPermission` directory is not detected as delta change between branches.

## Execution context
**node version:** node-v18.15.0
**git version:** 2.42.0.windows.2
**sfdx version:** sfdx-cli/7.209.6 win32-x64 
**sgd plugin version:** 5.26.2

**Comment by scolladon** [comment]
Hi @trudzki-al !

Thanks for raising this issue and thanks for contributing in making this project better!

I think the issue is because the [Custom Permission folder needs an 's'](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_custompermission.htm#:~:text=stored%20in%20the-,customPermissions,-folder.) (`customPermissions`)
Could you try with `customPermissions` folder and let us know ?

**Comment by trudzki-al** [comment]
You are of course totally right 😄, I am terribly ashamed for raising issue because of that oversight. Anyway thank you for instant resolving my problem.

**Comment by scolladon** [comment]
No problem at all @trudzki-al 

There is no bad questions, only bad answers :) 
Glad I could help here

Happy incremental deployment
