### ISSUE TITLE
[OuputFolderOnTheFly] Non-existent folders should be created

### ISSUE THREAD

**Issue by hassanalamibmx** [scolladon/sfdx-git-delta#75]
### Is your proposal related to a problem?

---

I want the `sgd:source:delta` command to export the delta to a folder with date and time in the folder name.
With a command that be similar to this
```powershell
sfdx sgd:source:delta --generate-delta --to HEAD --from HEAD^ --output .\manifest\patch-"$((Get-Date).tostring("dd-MM-yyyy-hh-mm-ss"))"
```
the command returns:
```json
{
  "error": ".\\manifest\\patch-05-11-2020-11-08-59 folder does not exist",
  "output": ".\\manifest\\patch-05-11-2020-11-08-59",
  "success": false,
  "warnings": null
}
```

### Describe the solution you'd like

---

Non-existent folders should be automatically created. I think most users expects the folder to be created as a default behavior.

### Describe alternatives you've considered

---

I created a custom ps script that stores the folder name in a variable, before creating it  and passing the variable to the `sfdx sgd:source:delta`

**Comment by scolladon** [comment]
Hi @hassanalamibmx !

Thanks for your interest in the product!
And thanks for this enhancement request!

This is something we thought with @mehdisfdc and we decided not to create the output.
For security reason it is best that the output folder already exist.
We don't want the tool to create folder where it should not in case it has been installed by an admin on a machine (so full right) and is used by normal user (with scoped right).

So this behaviour is by design.

If you can give us a little bit more of context maybe we can help you with an elegant workaround to automatize stuff (like creating the folder in the repo and keep it using [.gitkeep trick](https://dev.to/n350071/git-keep-empty-directory-by-gitkeep-aj1))
