### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by kigorman4sf** [scolladon/sfdx-git-delta#85]
Hello,
Installation command generate the following error:
` kigorman$ sfdx plugins:install sfdx-git-delta
This plugin is not digitally signed and its authenticity cannot be verified. Continue installation y/n?: y
Finished digital signature check.
error sfdx-git-delta@4.1.1: The engine "node" is incompatible with this module. Expected version ">=14.6.0". Got "12.18.3"
error Found incompatible module.
Installing plugin sfdx-git-delta... failed
    Error: yarn add sfdx-git-delta@latest --non-interactive --mutex=file:/Users/kigorman/.local/share/sfdx/yarn.lock 
    --preferred-cache-folder=/Users/kigorman/Library/Caches/sfdx/yarn --check-files exited with code 1`
SFDX version is
`$ sfdx --version
sfdx-cli/7.82.0-3d0c527ac6 darwin-x64 node-v12.18.3`
Node version 
`$ node --version
v15.5.1
`
It looks like the CLI node embedded version is lower than the one installed in standalone and also the one required by the plugin.

**Comment by mehdisfdc** [comment]
Hi @kigorman4sf 
Yes, you are correct to state that _It looks like the CLI node embedded version is lower than the one installed in standalone and also the one required by the plugin._
Until the node version is upgraded in the CLI installer, the solution is to install the CLI with npm rather than with the installer.

You should be able to solve your issue by:

1. Uninstalling the Salesforce CLI
2. Re-installing via npm (rather than with another installer): https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli.htm#sfdx_setup_install_cli_npm

**Comment by MayTheSForceBeWithYou** [comment]
How to uninstall sfdx on Mac OSX for step 1 of @mehdisfdc 's post:
https://gist.github.com/dcarroll/318e5f2d44fb6c2e612dd8d817473cdb
