### ISSUE TITLE
[Field Level Security on Orchestration Item ( of vlocity managed package ) does not get promoted for Profiles]

### ISSUE THREAD

**Issue by shkalantaryCL** [scolladon/sfdx-git-delta#890]
Issue verification check:

- [ ] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command? Yes

## What is the problem?

---
We are using the 
[Jenkins Console Log.txt](https://github.com/user-attachments/files/16133747/Jenkins.Console.Log.txt)
Scolladon invoked from our Jenkins pipeline. We use SF cli commands to push the changes to our orgs within the same Jenkins pipeline. attached is a console log from promotion of one profile, this does not promoted the FLS on the profile for the Orchestration item, however we have tried below alternate methods and they do promote the same FLS with a profile deployment to the same obj.
-Workbench
-SF CLi via VS code

### What is the expected result?

FLS of the profile on the orchestration item obj gets updated in the target org

### What is the actual result?

FLS of the profile on the orchestration item obj does not get updated in the target org and audit trail also does not show any traces of such update

## Steps to reproduce

---

issue has been isolated and a sample log is attached.

## Execution context

---

**Operating System:** …

**yarn version:** …

**node version:** …

**git version:** …

**sfdx version:** …

**sgd plugin version:** …

**Comment by shkalantaryCL** [comment]
[Orch Items Case.docx](https://github.com/user-attachments/files/16133798/Orch.Items.Case.docx)

**Comment by scolladon** [comment]
Hi @shkalantaryCL !

Thanks for raising this issue and thanks for contributing in making this project better!

From what I read inside the docx file, there has been made a "dummy" commit to the profile so it is picked up and deployed.
What is the content of the commit ?
Profile are metadata that are very specific in Salesforce because when a right is removed it is not retrieved with a false value, it is just not retrieved. And also it accept partial deployments, meaning it will change only the content of what is deployed (unlike permission set).
It means to deploy a disabled attribution, it needs to be done in the file before deploying the profile as it is not retrievable.

Also, the plugin scope the content of the profile with only what has been changed in the file.
This way the deployment is faster and scoped to only what needs to be deployed.

If those explanation does not help you in this situation and you still think there is an issue, please isolate and reproduce the issue in the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground) and share the branch, I'll have a look at it !

**Comment by scolladon** [comment]
Hi @shkalantaryCL !

I close this investigation because it has been idle for 2 weeks.

Feel free to reopen it with more information, as asked in the previous comment.
