### ISSUE TITLE
RecordType deletions are not being detected

### ISSUE THREAD

**Issue by HyruleConsulting** [scolladon/sfdx-git-delta#891]
Issue verification check:

- [x] is the current repository fully deployable at the commit SHA provided with the 'from' parameter of the command?

## What is the problem?
I have noticed that deletion of Record Types are not being detected by the command and included in the destructiveChanges.xml output. Other metadata types seem to work fine though and this issue is specific to /recordTypes/* 

---

### What is the parameter and the value you used with it?

`sf sgd source delta --from HEAD^1 --to HEAD --output .`

### What is the expected result?

destructiveChanges.xml
`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Account.ABC_MyRecordType__c</members>
        <name>RecordType</name>
    </types>
    <version>61.0</version>
</Package>`

### What is the actual result?

`<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <version>61.0</version>
</Package>`

## Steps to reproduce

---

delete a recordType from a valid sfdx project
commit the deletion
run `sf sgd source delta --from HEAD^1 --to HEAD --output .`
check the destructiveChanges.xml to see if the record type was included 

## Execution context

---

**Operating System:** …
MacOS (Sonama 14.5)

**yarn version:** …
1.22.19

**node version:** …
v20.10.0

**git version:** …
git version 2.40.0

**sfdx version:** …
@salesforce/cli/2.48.6 darwin-x64 node-v20.14.0

**sgd plugin version:** …
sfdx-git-delta 5.40.2

## More information (optional)

---

**Comment by scolladon** [comment]
Hi @HyruleConsulting !

Thanks for raising this issue and thanks for contributing in making this project better!

RecordTypes are not deleted because it is in fact [not possible](https://ideas.salesforce.com/s/idea/a0B8W00000GdeGKUAZ/allow-deletion-of-record-type-using-metadata-api) via metadata api... 

We had to create a specific treatment to handle this use case (cf [issue](https://github.com/scolladon/sfdx-git-delta/issues/620) and related [PR](https://github.com/scolladon/sfdx-git-delta/pull/631))

**Comment by HyruleConsulting** [comment]
Hi @scolladon 
Thank you for your response. We will make use of the --ignore-destructive flag and a .destructiveignore file then.

Many thanks for your work on this project, this is a fantastic tool. Closing for now

Kind regards
Adam of Hyrule
