### ISSUE TITLE
Package Generation with diff between Branches

### ISSUE THREAD

**Issue by sheldonleelazarus** [scolladon/sfdx-git-delta#91]
Hi

I have a question, can this tool generated packages when making a diff between branches?

Kind Regards
Sheldon Lazarus

**Comment by scolladon** [comment]
Hi @sheldonleelazarus !

Yes ! the tools works with any git sha pointer understandable by git itself.
Meaning, commit sha, branch, tag, git expression (HEAD, etc) works !

Seb

**Comment by osieckiAdam** [comment]
Hey @scolladon, just to make sure: Does this mean that I can handle the scenario when I create Pull Request, lets say with 9 files and my validation is starting. Then validation is failing and I need to add new file to Pull Request to make it work. In typical scenario only the latest commit is being compared so I need to add some dummy changes to my previously changes files to include them in new commit so that all of them will be validated. According to Your comment above this will be no longer the issue because I can compare the diffs between the branches, am I right?

**Comment by scolladon** [comment]
Hi @osieckiAdam !

If the diff is between the target branch and the current commit then yes.
It looks like a totally fine scenario and I would not be surprised if some project have already design something toward this approach using the command.
What do you think @mehdisfdc ?

Let us know what you'll come up with ! We can show case your pipeline if you want !

Seb

**Comment by mehdisfdc** [comment]
Yes, as @scolladon said, not only you can compare between commits in different branches, but you can also directly compare the branches.

Here are 2 examples:

**1) Comparing commits in different branches**
(from example, if you have commit fbc3ade6 in branch "develop" and commit 61f235b1 in branch "master")
`sfdx sgd:source:delta --to fbc3ade6 --from 61f235b1 --output .
`

**2) Comparing branches**
`sfdx sgd:source:delta --to develop --from master --output .`
