### ISSUE TITLE
Lack of several metadata types in package.xml

### ISSUE THREAD

**Issue by ArielS1** [scolladon/sfdx-git-delta#961]
Yesterday we upgraded the repo to v5.50.0 from v5.42.1 and we noticed that the package.xml that was generated on the same change was smaller, 
and several metadata type changed weren't detected even that we saw in the logs that the script detected changes in those files.

for example:
CustomLabel
CustomObjectTranslation
Profile
SharingRules
SharingCriteriaRule
StandardValueSetTranslation
Translation

then we installed the previous version v5.49.4 and it worked correctly

**Comment by scolladon** [comment]
Hi @ArielS1 !

Thanks for raising this issue and thanks for contributing in making this project better!

If I understand, in the v5.50.0 (`latest`) of the plugin there is no more detection of those metadata type, where in v5.42.1 (or `stable`) it works, right ?
If so, could you help me reproduce locally with your specific use case please ?

**Comment by scolladon** [comment]
> Did you try running the script on v5.50.0 on one of the metadata types i mentioned?

Yes ! We [have a lot](https://github.com/scolladon/sfdx-git-delta/actions/runs/12231337086/job/34115671738) of unit test / integration test and functional test.
That is why I ask for way to reproduce the issue as you see it (maybe with particular metadata or operating system or environment or file structure)

Could you help me reproduce the issue locally ?
You can either describe what commit content I should create inside a repository, or you could also fork the [reproduction playground](https://github.com/scolladon/sfdx-git-delta-reproduction-playground), create a branch, write the necessary commit to reproduce and share that branch here.
And give me the commands to run with sgd to reproduce the issue.

**Comment by scolladon** [comment]
Hi @ArielS1 !

Kind follow up to my previous message [here](https://github.com/scolladon/sfdx-git-delta/issues/961#issuecomment-2532070067)

Do you have a way to reproduce the issue locally ?
I'd like to investigate and fix the potential issue here ?

**Comment by scolladon** [comment]
Hi @ArielS1 !

One last follow up on this matter.
Do you have more information so I can reproduce the issue ? Any chance you could answer my previous messages and give me more details and detailed reproduction scenario ?
:)

**Comment by thomas100z** [comment]
Hi @scolladon,

I think I am experiencing something similar.  For me profiles are not included. However only for a specific command;
-  `sfdx sgd:source:delta --to "HEAD" --from "origin/staging" --output changed-sources/ --generate-delta --source force-app/ `  Includes profiles as expected.
- `sfdx sgd:source:delta --to "." --from "origin/staging" --output changed-sources/ --generate-delta --source force-app/            `   does not include profiles.

Is this by design? Am I misinterpreting how "." should be used?

I'm on version 5.52.0 running it locally  on Ubuntu 22.04.

Thanks for your time!

**Comment by scolladon** [comment]
What do you expect "." should do ?

**Comment by thomas100z** [comment]
My use case is comparing local, not yet commited changes, to a remote branch.  For other metadata types uncommited local changes are present when I run the command.

**Comment by scolladon** [comment]
I'm afraid it is not possible for now @thomas100z 😞 

Currently the plugin uses `git diff <from> <to>`
In order to do what you ask the plugin would have to ignore the `--to` parameter (TBD how / when as it defaults to "HEAD" when not filled => potential breaking changes) and then use `git diff <from>` 

What you can do is create a temporary commit locally to use sgd.
And just soft reset to the previous commit when you are done.

**Comment by scolladon** [comment]
If you really think it should be handled by the plugin then please create a feature request @thomas100z 😃 
It is definitely something we could do soon.
I have thought about it and it could be done without breaking changes IMHO

**Comment by thomas100z** [comment]
Thanks for the clarification @scolladon 

Let me preface that I have no experience with git diff from CLI. But the thing is it works for other metadata types.

For example;
1. Change a CustomField
2. Don't commit and don't deploy changes
3. `sfdx sgd:source:delta --to "." --from "origin/staging" --output changed-sources/ --generate-delta --source force-app/`
4. Field change is reflected in the generated delta package.


So this initially led me to believe it worked fine, until I noticed it does not for profiles.


In my use cases I can do your suggestion of a soft reset. So thanks for pointing that out!

**Comment by scolladon** [comment]
That's amazing that "." is working and pass the git sha pointer...
In fact it is a bug because it let the user think everything works because there is not issue but the behavior is not what is expected...
I'll fix it soon as it is much more serious when used with the `--from` parameter and may have strange behaviour


> In my use cases I can do your suggestion of a soft reset. So thanks for pointing that out!

Cool !

**Comment by scolladon** [comment]
I have proposed a fix for "." `--to` or `--from` parameter
And also by default it takes the uncommitted work
You can test the beta package in the PR if you want @thomas100z #985

**Comment by thomas100z** [comment]
Wow, that was quick ! @scolladon 

I tried it out. Now profiles are included 🙌🏻

However, I noticed new files are not. Is that expected behavior?
